version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "127.0.0.1:27017:27017"
  # Uncomment below lines for production
  #node:
  #  build: .
  #  restart: always
  #  ports:
  #    - 3000:3000